on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day

concurrency: ci-${{ contains(github.ref, 'refs/tags/') && 'production' || github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Run bot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Typecheck
        run: pnpm typecheck

      - name: Run bot
        id: run-bot
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          GITHUB_TOKEN: ${{ github.token }}
          BOT_PK: ${{ secrets.BOT_PK }}
        run: pnpm start
